INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) VALUES('NGUYEN 1', 'TAM 1');
INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) VALUES('NGUYEN 2', 'TAM 2');
INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) VALUES('NGUYEN 3', 'TAM 3');